version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: school-postgres
    restart: always
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: school_admin
      POSTGRES_PASSWORD: StrongPass123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U school_admin -d schooldb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: gin-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
